version: '2'

services:
  kafka_example_zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    hostname: kafka_example_zookeeper
    container_name: kafka_example_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./kafka_docker/zoo/data:/var/lib/zookeeper/data
      - ./kafka_docker/zoo/log:/var/lib/zookeeper/log

  kafka_example_broker:
    image: confluentinc/cp-kafka:5.4.1
    hostname: kafka_example_broker
    container_name: kafka_example_broker
    depends_on:
      - kafka_example_zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'kafka_example_zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_example_broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:

      - ./kafka_docker/broker/data:/var/lib/kafka/data

  kafka-example_init:
    image: confluentinc/cp-kafka:5.4.1
    depends_on:
      - kafka_example_broker
      - kafka_example_zookeeper
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka_example_broker:29092 --list
      
      echo 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka_example_broker:29092 --create --topic kafka_example_input_1 --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka_example_broker:29092 --create --topic kafka_example_input_2 --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka_example_broker:29092 --create --topic kafka_example_input_3 --replication-factor 1 --partitions 1

      kafka-topics --bootstrap-server kafka_example_broker:29092 --create --topic kafka_example_output_1 --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka_example_broker:29092 --create --topic kafka_example_output_2 --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka_example_broker:29092 --create --topic kafka_example_output_3 --replication-factor 1 --partitions 1
      
      
      echo 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka_example_broker:29092 --list
      "
